In [25]:
import numpy as geek

In [26]:
teste = geek.array([[1, 2, 3],[4, 5, 6]])

In [27]:
print(teste)

[[1 2 3]
 [4 5 6]]


In [88]:
teste2 = np.array([[1, 2, 3, 4],[12, 1, 2, 5], [11, 4, 3, 6],[10, 9, 8, 7]])

In [89]:
print(teste2)

[[ 1  2  3  4]
 [12  1  2  5]
 [11  4  3  6]
 [10  9  8  7]]


In [90]:
teste3 = np.array([[teste2[0][1], teste2[0][2], teste2[0][3], teste2[1][3]], [teste2[0][0], teste2[1][2], teste2[2][2], teste2[2][3]],
         [teste2[1][0], teste2[1][1], teste2[2][1], teste2[3][3]], [teste2[2][0], teste2[3][0], teste2[3][1], teste2[3][2]]])

In [91]:
print(teste3)

[[ 2  3  4  5]
 [ 1  2  3  6]
 [12  1  4  7]
 [11 10  9  8]]


In [92]:
teste4 = np.array([[teste3[0][1], teste3[0][2], teste3[0][3], teste3[1][3]], [teste3[0][0], teste3[1][2], teste3[2][2], teste3[2][3]],
         [teste3[1][0], teste3[1][1], teste3[2][1], teste3[3][3]], [teste3[2][0], teste3[3][0], teste3[3][1], teste3[3][2]]])

In [93]:
print(teste4)

[[ 3  4  5  6]
 [ 2  3  4  7]
 [ 1  2  1  8]
 [12 11 10  9]]


In [70]:
import numpy as np

b = np.array([1, -1, -1, 1])

teste2[np.arange(4), b] += 10

TypeError: list indices must be integers or slices, not tuple

In [81]:
print(teste2)

SyntaxError: invalid syntax (<ipython-input-81-4f4a2ef38a30>, line 1)

In [97]:
import numpy as np
a = np.array([[1 ,2 ,3 ,4], [12, 1, 2, 5], [11, 4, 3, 6], [10, 9, 8, 7]])

print(a[np.arange(4),])


[[ 1  2  3  4]
 [12  1  2  5]
 [11  4  3  6]
 [10  9  8  7]]


In [98]:
print(teste3)

[[ 2  3  4  5]
 [ 1  2  3  6]
 [12  1  4  7]
 [11 10  9  8]]


In [99]:
print(teste4)

[[ 3  4  5  6]
 [ 2  3  4  7]
 [ 1  2  1  8]
 [12 11 10  9]]
