# Exercícios Numpy

## Problema 1. 
Crie um vetor nulo de tamanho 10.

In [64]:
import numpy as np
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Problema 2. 
Como encontrar o tamanho da memória de qualquer matriz.

In [71]:
import numpy as np
n = np.zeros(10)
print("%d bytes" % (n.size * n.itemsize))

80 bytes


## Problema 3. 
Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1.

In [61]:
import numpy as np
n = np.zeros(10)
n[4]=1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Problema 4.
Crie um vetor com valores que variam de 10 a 49.

In [4]:
import numpy as np
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#por que o for nao funciona?
import numpy as np

#for i in range(1,5):
#    n[0][i]=rd.randint(10,50)

for i in range(0, 40):
    for j in range(10,50):
        n[i]=j
print(n)

[49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49
 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49 49]


## Problema 5.
Inverter um vetor (o primeiro elemento se torna o último).

In [7]:
import numpy as np
n = np.arange(1,10)
nr=n[::-1]
print(n)
print(nr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


## Problema 6. 
Crie uma matriz 3x3 com valores que variam de 0 a 8.

In [1]:
import numpy as np
n = np.

## Problema 7.
Encontre índices de elementos diferentes de zero em `[1,2,0,0,4,0]`.

## Problema 8.
Crie uma matriz de identidade 3x3.

In [3]:
import numpy as np
n = np.eye(3,3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Problema 9.
Crie uma matriz 3x3x3 com valores aleatórios.

In [7]:
import numpy as np
n = np.random.rand(3,3,3)
print(n)

[[[0.16526096 0.4936421  0.68187411]
  [0.49197431 0.05527148 0.68198432]
  [0.64241368 0.05994763 0.70146881]]

 [[0.45788701 0.99249058 0.34303585]
  [0.57161989 0.58504229 0.97437532]
  [0.2465478  0.28974888 0.3686968 ]]

 [[0.050136   0.53613811 0.34655328]
  [0.11531712 0.55869704 0.53244735]
  [0.69494057 0.01250666 0.34416133]]]


## Problema 10. 
Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo.

In [10]:
import numpy as np
n = np.random.rand(10,10)
print(n)


SyntaxError: invalid syntax (<ipython-input-10-804f5bfa3922>, line 4)

## Problema 11.
Crie um vetor aleatório de tamanho 30 e encontre o valor médio.

In [15]:
import numpy as np
n = np.random.rand(30,1)
print(n)


[[0.70192273]
 [0.1488847 ]
 [0.60632551]
 [0.22656386]
 [0.99620755]
 [0.83003126]
 [0.40415502]
 [0.46959975]
 [0.74620569]
 [0.68312372]
 [0.93131002]
 [0.53070625]
 [0.37336592]
 [0.79247071]
 [0.57013153]
 [0.93094097]
 [0.59889828]
 [0.55057996]
 [0.2298797 ]
 [0.17965118]
 [0.10032904]
 [0.42320987]
 [0.28808517]
 [0.22678079]
 [0.34120426]
 [0.3232859 ]
 [0.77355271]
 [0.70263461]
 [0.44822644]
 [0.93827718]]


## Problema 12.
Crie uma matriz 2D com 1 na borda e 0 dentro.

## Problema 13.
Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal.

## Problema 14. 
Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b).

## Problema 15. 
Subtrair a média de cada linha de uma matriz.

## Problema 16.
Como encontrar o valor mais frequente em uma matriz?

## Problema 17.
Crie uma matriz com valores aletaórios e salve para um arquivo.

## Problema 18.
Crie uma matriz a partir de um arquivo.